name: Close Issues with Status Stale Label

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight
  workflow_dispatch:    # Allows manual triggering

jobs:
  close-issues:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Close Issues
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LABEL_NAME: 'Status: Stale'
        CUSTOM_MESSAGE: 'Appologies that we were unable to address this issue in a timely manner! Given that we have millions of free users this has been a challenge that we are working on over time. This issue is being closed in order to allow us to focus on resolving more recently active issues. If this issue is still meaningful, please feel free to comment an update and re-open the issue for troubleshooting! Thanks for your continued loyalty to the StackBlitz platform over the years!'
      run: |
        curl -H "Authorization: token $GITHUB_TOKEN" \
             -H "Accept: application/vnd.github.v3+json" \
             "https://api.github.com/repos/$GITHUB_REPOSITORY/issues?state=open" \
             -o issues.json

        cat issues.json | jq --arg LABEL_NAME "$LABEL_NAME" -c '.[] | select(.labels[]? | .name==$LABEL_NAME) | .number' | while read -r issue; do
          curl -X PATCH -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$issue" \
               -d "{\"state\": \"closed\", \"body\": \"$CUSTOM_MESSAGE\"}"
        done
        

